version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.1
    environment:
      - discovery.type=single-node
    ports: ['9200:9200', '9300:9300']
    networks: ['elk']

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.1
    ports: ['5601:5601']
    networks: ['elk']
    depends_on: ['elasticsearch']

  metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:7.1.1
    volumes:
      - ./metricbeat/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
    networks: ['elk']
    depends_on: ['logstash']

  logstash:
    build: 
      context: ./logstash
    ports: ['9600:9600']
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/templates/:/usr/share/logstash/templates/
    networks: ['elk']
    depends_on: ['elasticsearch']

networks: {elk: {}}
