version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.0
    environment:
      - discovery.type=single-node
    volumes:
      - ${ES01_DATA_FOLDER}:/usr/share/elasticsearch/data
    ports: ['9200:9200', '9300:9300']
    networks: ['elk']

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.5.0
    ports: ['5601:5601']
    networks: ['elk']
    depends_on: ['elasticsearch']

  metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:7.5.0
    volumes:
      - ./metricbeat/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
    environment:
      - HUE_HUB_IP=${HUE_HUB_IP}
      - HUE_API_KEY=${HUE_API_KEY}
    networks: ['elk']
    depends_on: ['logstash']

  logstash:
    build: 
      context: ./logstash
    ports: ['9600:9600']
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/templates/:/usr/share/logstash/templates/
    environment:
      - SLACK_ENDPOINT=${SLACK_ENDPOINT}
    networks: ['elk']
    depends_on: ['elasticsearch']

networks: {elk: {}}
