metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.modules:
- module: http
  metricsets: 
    - json
  hosts: ["${HUE_HUB_IP}"]
  namespace: "json_namespace"
  path: "/api/${HUE_API_KEY}/lights"
  method: "GET"
  period: 30s
  enabled: true

processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
